# joint_limits.yaml
joint_limits:
  slider_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1000.0
