planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0  # Max motion added to tree. Best left to 0.0 (default)
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar
actuator_group:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
